### ISSUE TITLE
type url.URL has no field or method Raw

### ISSUE THREAD

**Issue by zyxar** [pomack/thrift4go#12]
in `compiler/cpp/src/generate/t_go_genetator.cc`, line 1769, should _parsedUrl.Raw_ be replaced by **parsedUrl.RawQuery**?

**Comment by pomack** [comment]
Darn, thought I fixed all the r60 -> go1 issues as far as getting it compiling went.  Should've been parsedUrl.String()

I've updated the code and pushed it out.
