### ISSUE TITLE
Travis-CI build failure

### ISSUE THREAD

**Issue by pomack** [pomack/thrift4go#28]
The following line seems to be failing at http://travis-ci.org/#!/pomack/thrift4go/builds/1930665

  `sudo apt-get remove -y --force-yes --purge golang-tip || true`

**Comment by matttproud** [comment]
Weird.  The `|| true` should be preventing it from barfing.  I think there is something that you can manually do with the Github commit hooks to forcibly trigger another build.  Would you mind trying that again to see if this can be repeated?

**Comment by pomack** [comment]
Still failing.

**Comment by matttproud** [comment]
We should be able to close this issue now.  :-)
