### ISSUE TITLE
generated code import thrift4go lib path

### ISSUE THREAD

**Issue by GeertJohan** [pomack/thrift4go#54]
Hi all,

Right now, generated code gets generated with an `import "thrift"` statement (or grouped import).
`thrift` is then used as package reference throughout the generated code.
This means that the package is not downloaded using `go get` but has to be manually installed.
I prefer package installation through go get, in this case: `go get github.com/pomack/thrift4go/lib/go/src/thrift`

At this moment, a script I use substitutes all `"thrift"` import statements with `"github.com/pomack/thrift4go/lib/go/src/thrift"` to make the generated code working. Are you doing this different?
If not: shouldn't the compiled code contain the full path in the import statement?

The tricky thing is that during tests (both local and travis-ci) you would want to test the thrift4go lib "locally". Because if a test would use a go-getted thrift4go lib, it would use the one that has the tag `go1` in the pomack:master repo. So if the code generator would be changed to put `github.com/pomack/thrift4go/lib/go/src/thrift` in the imports, then there should be a switch for automated tests to use the local `thrift` instead.

Throughts?

**Comment by GeertJohan** [comment]
_I'd be happy to dive in the code and make any changes if a full path with switch for testing turns out to be the best solution.._

**Comment by pomack** [comment]
There are two aspects to this.
    1. `thrift4go` as a standalone component that can be updated incrementally
    2. `thrift4go` becoming a full component of the official Apache Thrift project

We are currently at stage 1, but I'd like to get to stage 2.

To be a part of stage 2, `thrift` should be the library that gets installed and used accordingly.  Using `go get` is important for standalone packages, but the goal of this project was always to be included in the official distribution.  I haven't had the time to get `thrift4go` into the mainline project, but it really should be there.

One more thing, we don't want to use the tag `go1`, but would rather use the branch `go1`.

**Comment by GeertJohan** [comment]
I totally agree that thrift4go should become a full component of the official Apache Thrift project at one point.
But wouldn't it be good if the library is still available through `go get`? Even if the project arrives at stage 2?
Because otherwise the user would have to use a relative path to where he/she has Apache Thrift installed, which will break go-get-able libraries (for example: gossie). The downside of using _this_ repository (github.com/pomack/thrift4go) is that it's only the latest version (go1 branch), while a project might be depending on a certain version of thrift (v0.8.0. for instance). Of-course a solution to that would be a new repo containing the thrift4go lib at each release version.. So you could go get and import the lib like:
`github.com/thrift4go/0.8.0/thrift` and
`github.com/thrift4go/0.9.0/thrift`
That way, one can be sure to have the same stable thrift4go lib that a package was developed with.

But, we're not at stage 2 yet. Do you think it will take long for thrift4go to get into the official project? I believe there are still a bunch of problems to solve. Bug fixes. And enhancements that are easy to get in now, but will be harder to do once it's accepted in the official project. It will probably take some time before thrift4go gets accepted by Apache too.
With the earlier idea of github repositories containing a certain release version, I think the code generator/compiler should always use a go-get-able path. In both stage 1 and stage 2. It will make development easier, now and at stage2.
As for the 'switch' I talked about in the opening post, that isn't really necessary, the tests Makefile can simply fake the go get behaviour.

How do you think about this now?

tag vs. branch: you're right, branch.

**Comment by GeertJohan** [comment]
Created quick'n'dirty example/test at github.com/thrift4go/thrift4go-lib-0.9.0
Which is go-get-able like "github.com/thrift4go/thrift4go-lib-0.9.0/thrift"

**Comment by pomack** [comment]
I think if they want a particular version, they should be able to go get the library but then soft-link it to thrift in their GOPATH

**Comment by GeertJohan** [comment]
Ah ofcourse. I've added that method in the readme.md and made a pull request here: https://github.com/pomack/thrift4go/pull/55
