### ISSUE TITLE
Failing Go tests when building Thrift 

### ISSUE THREAD

**Issue by ghost** [pomack/thrift4go#63]
Trying to build thrift:
./configure --with-go
make

And I'm getting the following failed tests:
=== RUN TestNonblockingTransportServerToClient
--- FAIL: TestNonblockingTransportServerToClient (0.00 seconds)
    ttransport_test.go:61: Transport *thrift.TFramedTransport cannot flush write of binary data: write tcp 127.0.0.1:62561: i/o timeout
=== RUN TestNonblockingTransportClientToServer
--- FAIL: TestNonblockingTransportClientToServer (0.00 seconds)
    ttransport_test.go:61: Transport *thrift.TFramedTransport cannot flush write of binary data: write tcp 127.0.0.1:40001: i/o timeout

I'm using Go 1.1.1 and downloaded thrift 0.9.0

**Comment by GeertJohan** [comment]
I believe development of thrift for Go is continued at traviscline/thrift. That repo contains the latest thirft with pomack's code merged into it and additions. It is a great attempt to get Go back in the main thrift repo. Lots of improvements are being made by traviscline.

**Comment by ghost** [comment]
Thanks, Ill use that instead :-)
